services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-somepassword}
      - POSTGRES_DB=${POSTGRES_DB:-postgres18}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  postgres_data:
