services:
  postgres:
    build: .
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-somepassword}
      - POSTGRES_DB=${POSTGRES_DB:-postgres18}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-defaultredispass}
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-defaultredispass}

volumes:
  postgres_data:
  redis_data: